//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodBooking.DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailsId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual FoodMenu FoodMenu { get; set; }
        public virtual Order Order { get; set; }
    }
}
